pipeline {
    agent {
        label 'docker'  // Теперь используем нового агента
    }
    
    stages {
        stage('Build') {
            steps {
                sh 'docker run --rm node:18-alpine node --version'
                sh 'docker run --rm -v $PWD:/app -w /app node:18-alpine npm install'
            }
        }
        
        stage('Test') {
            steps {
                sh 'docker run --rm -v $PWD:/app -w /app node:18-alpine npm test'
            }
        }
        
        stage('Deliver') {
            steps {
                sh 'docker run --rm -v $PWD:/app -w /app node:18-alpine npm run build'
            }
        }
    }
}
